name: macOS Deployment Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: macos-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
  deploy:
    runs-on: macos-latest
    needs: build
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Deploy to macOS
        run: |
          /opt/homebrew/bin/git config --global --add safe.directory /Users/runner/work/runner-images/runner-images
          /opt/homebrew/bin/git config --local --name-only --get-regexp core\.sshCommand
          /opt/homebrew/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
          /opt/homebrew/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
          http.https://github.com/.extraheader
          /opt/homebrew/bin/git config --local --unset-all http.https://github.com/.extraheader
          /opt/homebrew/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
