name: macOS Deployment Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: macos-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
  deploy:
    runs-on: macos-latest
    needs: build
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
